apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nours-test-app
  description: This is just a test app
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: the-one-man-show
